### ISSUE TITLE
Command ZDO_AUTO_FIND_DESTINATION

### ISSUE THREAD

**Issue by martibenj** [zigbeer/cc-znp#11]
It seems that cc-znp miss the ZDO_AUTO_FIND_DESTINATION command and ZDO_NEW_DSTADDR_IND indicator.
Am I missing something or is it only the wiki that is out of date ?
The ref doc [Z-Stack Monitor and Test API.pdf](https://github.com/zigbeer/cc-znp/files/2680028/Z-Stack.Monitor.and.Test.API.pdf) , check p.100 about the command

Thx

**Comment by jackchased** [comment]
Hi @martibenj, the **ZDO_AUTO_FIND_DESTINATION** command has been implemented, but the wiki missing this command. I have already added it to [ZDO Indication Table](https://github.com/zigbeer/cc-znp/wiki/6.-Z-Stack-MT-API-Reference-Tables#zdo-indication).

The **ZDO_NEW_DSTADDR_IND** indicator in Z-Stack Monitor and Test API document as follow. It does not provide the AREQ parameters, so it cannot be implemented.

![image](https://user-images.githubusercontent.com/14177449/50136400-a409bc80-02d2-11e9-9e98-49ff5698258b.png)

**Comment by martibenj** [comment]
Thx for the information !
