### ISSUE TITLE
Check if cc-znp do have the new MT commands or REQ/RSP corrections

### ISSUE THREAD

**Issue by simenkid** [zigbeer/cc-znp#3]
Please check these commands and ensure their arguments and responses again.

* MT_SYS:
    * SYS_ZDIAGS_INIT_STATS
    * SYS_ZDIAGS_CLEAR_STATS
    * SYS_ZDIAGS_GET_STATS
    * SYS_ZDIAGS_RESTORE_STATS_NV
    * SYS_ ZDIAGS_SAVE_STATS_TO_NV
    * SYS_NV_CREATE
    * SYS_NV_DELETE
    * SYS_NV_READ
    * SYS_NV_WRITE
    * SYS_NV_UPDATE
    * SYS_NV_COMPACT

* MT_UTIL:
    * UTIL_KEY_EVENT  (check if something changed?)

* MT_ZDO:
    * ZDO_SET_REJOIN_PARAMETERS_REQ
    * ZDO_SEC_ADD_LINK_KEY
    * ZDO_SEC_ENTRY_LOOKUP_EXT
    * ZDO_SEC_DEVICE_REMOVE
    * ZDO_EXT_ROUTE_DISC
    * ZDO_EXT_ROUTE_CHECK
    * ZDO_EXT_REMOVE_GROUP
    * ZDO_EXT_REMOVE_ALL_GROUP
    * ZDO_EXT_FIND_ALL_GROUPS_ENDPOINT
    * ZDO_EXT_FIND_GROUP
    * ZDO_EXT_ADD_GROUP
    * ZDO_EXT_COUNT_ALL_GROUPS
    * ZDO_EXT_RX_IDLE
    * ZDO_EXT_UPDATE_NWK_KEY
    * ZDO_EXT_SWITCH_NWK_KEY
    * ZDO_EXT_NWK_INFO
    * ZDO_EXT_SEC_APS_REMOVE_REQ
    * ZDO_FORCE_CONCENTRATOR_CHANGE
    * ZDO_EXT_SET_PARAMS

**Comment by jackchased** [comment]
I checked these commands, and added the new MT commands, which cc-znp don't have.
